[package]
name = "command-rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# my_workspace/Cargo.toml

[lib]
name = "command_rpc"
crate-type = ["cdylib"]

# [workspace]
# members = [
    # "crpc",
    # "crpc-mark-macro",
    # "traverse",
# ]

[dependencies]
crpc = { version = "*", path = "./crpc" }
crpc-mark-macro = { version = "*", path = "./crpc-mark-macro"}
traverse = { version = "*", path = "./traverse"}