[package]
name = "command-rpc"
version = "0.1.7"
edition = "2021"
description = "This is a rpc service which is not ready yet but needs to be published because of testing purposes."
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# my_workspace/Cargo.toml

[lib]
name = "command_rpc"
crate-type = ["dylib"]
path = "src/lib.rs"

# [workspace]
# members = [
#     "crpc",
#     "crpc-mark-macro",
#     "traverse",
# ]

[dependencies]
crpc = { version = "*", path = "./crpc" }
crpc-mark-macro = { version = "*", path = "./crpc-mark-macro" }
traverse = { version = "*", path = "./traverse" }