[package]
name = "command-rpc"
version = "0.1.2"
edition = "2021"
description = "This is a rpc service which is not ready yet but needs to be published because of testing purposes."
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# my_workspace/Cargo.toml

[lib]
# name = "command_rpc"
crate-type = ["dylib"]

[workspace]
members = [
    "crpc",
    "crpc-mark-macro",
    "traverse",
]

# [dependencies]
# crpc = { version = "*", git = "https://github.com/la-fourier/command-rpc/crpc.git" }
# crpc-mark-macro = { version = "*", path = ".https://github.com/la-fourier/command-rpc/crpc_mark_macro.git"}
# traverse = { version = "*", path = "https://github.com/la-fourier/command-rpc/traverse.git"}