[package]
name = "command-rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "command_rpc"
crate-type = ["cdylib"]

[dependencies]
regex = "1.7.3"
clap = "*"
quote = "*"
syn = "*"