[package]
name = "testcrate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comment_macro = { version = "*", path = "../comment_macro" }