[package]
name = "crpc"
version = "0.1.0"
edition = "2021"

[lib]
name = "crpc"
crate-type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.3"
clap = "*"
